<?php

namespace App\Http\Controllers;
use Illuminate\Routing\Controller as BaseController;
use App\Models\User;

class WelcomeController extends BaseController
{
    public function index()
    {
        return view('index');
    }

    public function about()
    {
        return view('about');
    }

    public function blogs()
    {
        return view('blogs');
    }

    public function contact()
    {
        return view('contact');
    }

    public function inovasi()
    {
        return view('inovasi');
    }

    public function inkubasi()
    {
        return view('inkubasi');
    }
    public function lab()
    {
        return view('lab');
    }

    public function exc()
    {
        return view('exc');
    }

    public function exclusive()
    {
        $galleries = [
            // EXCLUSIVE
            1 => [
                asset('assets/gallery/exclusive/pembangkit/pembangkit.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit1.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit2.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit3.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit4.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit5.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit6.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit7.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit8.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit9.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit10.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit11.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit12.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit13.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit14.jpg'),
                asset('assets/gallery/exclusive/pembangkit/pembangkit15.jpg'),
            ],
            2 => [
                asset('assets/gallery/exclusive/auditorium/auditorium.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium1.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium2.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium3.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium4.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium5.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium6.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium7.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium8.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium9.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium10.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium11.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium12.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium13.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium14.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium15.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium16.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium17.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium18.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium19.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium20.jpg'),
                asset('assets/gallery/exclusive/auditorium/auditorium21.jpg'),
            ],
            3 => [
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo1.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo2.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo3.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo4.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo5.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo6.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo7.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo8.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo9.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo10.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo11.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo12.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo13.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo14.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo15.jpg'),
                asset('assets/gallery/exclusive/sedyatmo/sedyatmo16.jpg'),
            ],
            4 => [
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen1.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen2.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen3.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen4.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen5.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen6.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen7.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen8.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen9.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen10.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen11.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen12.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen13.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen14.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen15.jpg'),
                asset('assets/gallery/exclusive/kantin_dosen/kantin_dosen16.jpg'),
            ],
        ];

        return view('exclusive', compact('galleries'));
    }

    public function laboratorium()
    {
        $galleries2 = [
            //FTEN
            1 => [
                asset('assets/gallery/ften/multi/multi.jpg'),
                asset('assets/gallery/ften/multi/multi1.jpg'),
                asset('assets/gallery/ften/multi/multi2.jpg'),
                asset('assets/gallery/ften/multi/multi3.jpg'),
                asset('assets/gallery/ften/multi/multi4.jpg'),
                asset('assets/gallery/ften/multi/multi5.jpg'),
                asset('assets/gallery/ften/multi/multi6.jpg'),
                asset('assets/gallery/ften/multi/multi7.jpg'),
                asset('assets/gallery/ften/multi/multi8.jpg'),
                asset('assets/gallery/ften/multi/multi9.jpg'),
            ],
            2 => [
                asset('assets/gallery/ften/saq/saq1.jpg'),
                asset('assets/gallery/ften/saq/saq2.jpg'),
                asset('assets/gallery/ften/saq/saq3.jpg'),
                asset('assets/gallery/ften/saq/saq4.jpg'),
                asset('assets/gallery/ften/saq/saq5.jpg'),
                asset('assets/gallery/ften/saq/saq6.jpg'),
                asset('assets/gallery/ften/saq/saq7.jpg'),
                asset('assets/gallery/ften/saq/saq8.jpg'),
            ],
            3 => [
                asset('assets/gallery/ften/se/se.jpg'),
                asset('assets/gallery/ften/se/se1.jpg'),
                asset('assets/gallery/ften/se/se2.jpg'),
                asset('assets/gallery/ften/se/se3.jpg'),
                asset('assets/gallery/ften/se/se4.jpg'),
                asset('assets/gallery/ften/se/se5.jpg'),
                asset('assets/gallery/ften/se/se6.jpg'),
                asset('assets/gallery/ften/se/se7.jpg'),
                asset('assets/gallery/ften/se/se8.jpg'),
                asset('assets/gallery/ften/se/se9.jpg'),
                asset('assets/gallery/ften/se/se10.jpg'),
            ],
            4 => [
                asset('assets/gallery/ften/ic/ic.jpg'),
                asset('assets/gallery/ften/ic/ic1.jpg'),
                asset('assets/gallery/ften/ic/ic2.jpg'),
                asset('assets/gallery/ften/ic/ic3.jpg'),
                asset('assets/gallery/ften/ic/ic4.jpg'),
                asset('assets/gallery/ften/ic/ic5.jpg'),
                asset('assets/gallery/ften/ic/ic6.jpg'),
                asset('assets/gallery/ften/ic/ic7.jpg'),
                asset('assets/gallery/ften/ic/ic8.jpg'),
                asset('assets/gallery/ften/ic/ic9.jpg'),
            ],
            5 => [
                asset('assets/gallery/ften/es/es.jpg'),
                asset('assets/gallery/ften/es/es1.jpg'),
                asset('assets/gallery/ften/es/es2.jpg'),
                asset('assets/gallery/ften/es/es3.jpg'),
                asset('assets/gallery/ften/es/es4.jpg'),
                asset('assets/gallery/ften/es/es5.jpg'),
                asset('assets/gallery/ften/es/es6.jpg'),
                asset('assets/gallery/ften/es/es7.jpg'),
                asset('assets/gallery/ften/es/es8.jpg'),
                asset('assets/gallery/ften/es/es9.jpg'),
                asset('assets/gallery/ften/es/es10.jpg'),
            ],
            6 => [
                asset('assets/gallery/ften/cn/cn1.jpg'),
                asset('assets/gallery/ften/cn/cn2.jpg'),
                asset('assets/gallery/ften/cn/cn3.jpg'),
                asset('assets/gallery/ften/cn/cn4.jpg'),
                asset('assets/gallery/ften/cn/cn5.jpg'),
                asset('assets/gallery/ften/cn/cn6.jpg'),
                asset('assets/gallery/ften/cn/cn7.jpg'),
                asset('assets/gallery/ften/cn/cn8.jpg'),
                asset('assets/gallery/ften/cn/cn9.jpg'),
            ],
            7 => [
                asset('assets/gallery/ften/ir/ir.jpg'),
                asset('assets/gallery/ften/ir/ir1.jpg'),
                asset('assets/gallery/ften/ir/ir2.jpg'),
                asset('assets/gallery/ften/ir/ir3.jpg'),
                asset('assets/gallery/ften/ir/ir4.jpg'),
                asset('assets/gallery/ften/ir/ir5.jpg'),
                asset('assets/gallery/ften/ir/ir6.jpg'),
                asset('assets/gallery/ften/ir/ir7.jpg'),
                asset('assets/gallery/ften/ir/ir8.jpg'),
            ],
            8 => [
                asset('assets/gallery/ften/itcc/itcc.jpg'),
                asset('assets/gallery/ften/itcc/itcc1.jpg'),
                asset('assets/gallery/ften/itcc/itcc2.jpg'),
                asset('assets/gallery/ften/itcc/itcc3.jpg'),
                asset('assets/gallery/ften/itcc/itcc4.jpg'),
                asset('assets/gallery/ften/itcc/itcc5.jpg'),
                asset('assets/gallery/ften/itcc/itcc6.jpg'),
                asset('assets/gallery/ften/itcc/itcc7.jpg'),
                asset('assets/gallery/ften/itcc/itcc8.jpg'),
                asset('assets/gallery/ften/itcc/itcc9.jpg'),
                asset('assets/gallery/ften/itcc/itcc10.jpg'),
                asset('assets/gallery/ften/itcc/itcc11.jpg'),
            ],
            9 => [
                asset('assets/gallery/ften/ldc/ldc.jpg'),
                asset('assets/gallery/ften/ldc/ldc1.jpg'),
                asset('assets/gallery/ften/ldc/ldc2.jpg'),
                asset('assets/gallery/ften/ldc/ldc3.jpg'),
                asset('assets/gallery/ften/ldc/ldc4.jpg'),
                asset('assets/gallery/ften/ldc/ldc5.jpg'),
                asset('assets/gallery/ften/ldc/ldc6.jpg'),
                asset('assets/gallery/ften/ldc/ldc7.jpg'),
                asset('assets/gallery/ften/ldc/ldc8.jpg'),
                asset('assets/gallery/ften/ldc/ldc9.jpg'),
                asset('assets/gallery/ften/ldc/ldc10.jpg'),
            ],
            10 => [
                asset('assets/gallery/ften/vr/vr.jpg'),
                // asset('assets/gallery/ften/vr/vr1.jpg'),
                // asset('assets/gallery/ften/vr/vr2.jpg'),
                // asset('assets/gallery/ften/vr/vr3.jpg'),
                // asset('assets/gallery/ften/vr/vr4.jpg'),
                // asset('assets/gallery/ften/vr/vr5.jpg'),
                // asset('assets/gallery/ften/vr/vr6.jpg'),
                // asset('assets/gallery/ften/vr/vr7.jpg'),
                // asset('assets/gallery/ften/vr/vr8.jpg'),
                // asset('assets/gallery/ften/vr/vr9.jpg'),
            ],

            //FTBE
            11 => [
                asset('assets/gallery/ftbe/metalurgi/metalurgi.jpg'),
                asset('assets/gallery/ftbe/metalurgi/metalurgi1.jpg'),
                asset('assets/gallery/ftbe/metalurgi/metalurgi2.jpg'),
                asset('assets/gallery/ftbe/metalurgi/metalurgi3.jpg'),
                asset('assets/gallery/ftbe/metalurgi/metalurgi4.jpg'),
                asset('assets/gallery/ftbe/metalurgi/metalurgi5.jpg'),
                asset('assets/gallery/ftbe/metalurgi/metalurgi6.jpg'),
                asset('assets/gallery/ftbe/metalurgi/metalurgi7.jpg'),
                asset('assets/gallery/ftbe/metalurgi/metalurgi8.jpg'),
                asset('assets/gallery/ftbe/metalurgi/metalurgi9.jpg'),
                asset('assets/gallery/ftbe/metalurgi/metalurgi10.jpg'),
            ],
            12 => [
                asset('assets/gallery/ftbe/se/se.jpg'),
                asset('assets/gallery/ftbe/se/se1.jpg'),
                asset('assets/gallery/ftbe/se/se2.jpg'),
                asset('assets/gallery/ftbe/se/se3.jpg'),
                asset('assets/gallery/ftbe/se/se4.jpg'),
                asset('assets/gallery/ftbe/se/se5.jpg'),
                asset('assets/gallery/ftbe/se/se6.jpg'),
                asset('assets/gallery/ftbe/se/se7.jpg'),
                asset('assets/gallery/ftbe/se/se8.jpg'),
                asset('assets/gallery/ftbe/se/se9.jpg'),
                asset('assets/gallery/ftbe/se/se10.jpg'),
                asset('assets/gallery/ftbe/se/se11.jpg'),
                asset('assets/gallery/ftbe/se/se12.jpg'),
            ],
            13 => [
                asset('assets/gallery/ftbe/pltu/pltu.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu1.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu2.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu3.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu4.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu5.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu6.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu7.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu8.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu9.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu10.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu11.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu12.jpg'),
                asset('assets/gallery/ftbe/pltu/pltu13.jpg'),
            ],
            14 => [
                asset('assets/gallery/ftbe/fenomena/fenomena.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena1.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena2.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena3.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena4.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena5.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena6.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena7.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena8.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena9.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena10.jpg'),
                asset('assets/gallery/ftbe/fenomena/fenomena11.jpg'),
            ],
            15 => [
                asset('assets/gallery/ftbe/pltmh/pltmh.jpg'),
                asset('assets/gallery/ftbe/pltmh/pltmh1.jpg'),
                asset('assets/gallery/ftbe/pltmh/pltmh2.jpg'),
                asset('assets/gallery/ftbe/pltmh/pltmh3.jpg'),
            ],

            //Vokasi
            16 => [
                asset('assets/gallery/vokasi/mechanic/bubut/bubut.jpg'),
                asset('assets/gallery/vokasi/mechanic/bubut/bubut1.jpg'),
                asset('assets/gallery/vokasi/mechanic/bubut/bubut2.jpg'),
                asset('assets/gallery/vokasi/mechanic/bubut/bubut3.jpg'),
                asset('assets/gallery/vokasi/mechanic/bubut/bubut4.jpg'),
                asset('assets/gallery/vokasi/mechanic/bubut/bubut5.jpg'),
                asset('assets/gallery/vokasi/mechanic/bubut/bubut6.jpg'),
                asset('assets/gallery/vokasi/mechanic/bubut/bubut7.jpg'),
                asset('assets/gallery/vokasi/mechanic/bubut/bubut8.jpg'),
                asset('assets/gallery/vokasi/mechanic/bubut/bubut9.jpg'),
                asset('assets/gallery/vokasi/mechanic/bubut/bubut10.jpg'),
            ],
            17 => [
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku1.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku2.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku3.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku4.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku5.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku6.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku7.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku8.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku9.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku10.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku11.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku12.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku13.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku14.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku15.jpg'),
                    asset('assets/gallery/vokasi/mechanic/kerja_bangku/kerja_bangku16.jpg'),
                ],

            // FKET
            21 => [
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro1.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro2.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro3.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro4.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro5.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro6.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro7.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro8.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro9.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro10.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro11.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro12.jpg'),
                asset('assets/gallery/fket/dasar_elektro1/dasar_elektro13.jpg'),
            ],
            22 => [
                asset('assets/gallery/fket/dasar_elektro2/dasar_elektro.jpg'),
                asset('assets/gallery/fket/dasar_elektro2/dasar_elektro1.jpg'),
                asset('assets/gallery/fket/dasar_elektro2/dasar_elektro2.jpg'),
                asset('assets/gallery/fket/dasar_elektro2/dasar_elektro3.jpg'),
                asset('assets/gallery/fket/dasar_elektro2/dasar_elektro4.jpg'),
                asset('assets/gallery/fket/dasar_elektro2/dasar_elektro5.jpg'),
                asset('assets/gallery/fket/dasar_elektro2/dasar_elektro6.jpg'),
                asset('assets/gallery/fket/dasar_elektro2/dasar_elektro7.jpg'),
                asset('assets/gallery/fket/dasar_elektro2/dasar_elektro8.jpg'),
                asset('assets/gallery/fket/dasar_elektro2/dasar_elektro9.jpg'),
            ],
            23 => [
                asset('assets/gallery/fket/dpl/dpl.jpg'),
                asset('assets/gallery/fket/dpl/dpl1.jpg'),
                asset('assets/gallery/fket/dpl/dpl2.jpg'),
                asset('assets/gallery/fket/dpl/dpl3.jpg'),
                asset('assets/gallery/fket/dpl/dpl4.jpg'),
                asset('assets/gallery/fket/dpl/dpl5.jpg'),
                asset('assets/gallery/fket/dpl/dpl6.jpg'),
                asset('assets/gallery/fket/dpl/dpl7.jpg'),
                asset('assets/gallery/fket/dpl/dpl8.jpg'),
                asset('assets/gallery/fket/dpl/dpl9.jpg'),
                asset('assets/gallery/fket/dpl/dpl10.jpg'),
                asset('assets/gallery/fket/dpl/dpl11.jpg'),
                asset('assets/gallery/fket/dpl/dpl12.jpg'),
                asset('assets/gallery/fket/dpl/dpl13.jpg'),
            ],
            24 => [
                asset('assets/gallery/fket/sistem_kontrol/sistem_kontrol.jpg'),
                asset('assets/gallery/fket/sistem_kontrol/sistem_kontrol1.jpg'),
                asset('assets/gallery/fket/sistem_kontrol/sistem_kontrol2.jpg'),
                asset('assets/gallery/fket/sistem_kontrol/sistem_kontrol3.jpg'),
                asset('assets/gallery/fket/sistem_kontrol/sistem_kontrol4.jpg'),
                asset('assets/gallery/fket/sistem_kontrol/sistem_kontrol5.jpg'),
                asset('assets/gallery/fket/sistem_kontrol/sistem_kontrol6.jpg'),
                asset('assets/gallery/fket/sistem_kontrol/sistem_kontrol7.jpg'),
                asset('assets/gallery/fket/sistem_kontrol/sistem_kontrol8.jpg'),
                asset('assets/gallery/fket/sistem_kontrol/sistem_kontrol9.jpg'),
            ],
            25 => [
                asset('assets/gallery/fket/electrical_machines/electrical_machines.jpg'),
                asset('assets/gallery/fket/electrical_machines/electrical_machines1.jpg'),
                asset('assets/gallery/fket/electrical_machines/electrical_machines2.jpg'),
                asset('assets/gallery/fket/electrical_machines/electrical_machines3.jpg'),
                asset('assets/gallery/fket/electrical_machines/electrical_machines4.jpg'),
                asset('assets/gallery/fket/electrical_machines/electrical_machines5.jpg'),
                asset('assets/gallery/fket/electrical_machines/electrical_machines6.jpg'),
                asset('assets/gallery/fket/electrical_machines/electrical_machines7.jpg'),
            ],
            26 => [
                asset('assets/gallery/fket/fluid_mechanics/fluid_mechanics.jpg'),
                asset('assets/gallery/fket/fluid_mechanics/fluid_mechanics1.jpg'),
                asset('assets/gallery/fket/fluid_mechanics/fluid_mechanics2.jpg'),
                asset('assets/gallery/fket/fluid_mechanics/fluid_mechanics3.jpg'),
                asset('assets/gallery/fket/fluid_mechanics/fluid_mechanics4.jpg'),
                asset('assets/gallery/fket/fluid_mechanics/fluid_mechanics5.jpg'),
                asset('assets/gallery/fket/fluid_mechanics/fluid_mechanics6.jpg'),
                asset('assets/gallery/fket/fluid_mechanics/fluid_mechanics7.jpg'),
                asset('assets/gallery/fket/fluid_mechanics/fluid_mechanics8.jpg'),
                asset('assets/gallery/fket/fluid_mechanics/fluid_mechanics9.jpg'),
            ],
            27 => [
                asset('assets/gallery/fket/electricity_magnetism/electricity_magnetism.jpg'),
                asset('assets/gallery/fket/electricity_magnetism/electricity_magnetism1.jpg'),
                asset('assets/gallery/fket/electricity_magnetism/electricity_magnetism2.jpg'),
                asset('assets/gallery/fket/electricity_magnetism/electricity_magnetism3.jpg'),
                asset('assets/gallery/fket/electricity_magnetism/electricity_magnetism4.jpg'),
                asset('assets/gallery/fket/electricity_magnetism/electricity_magnetism5.jpg'),
                asset('assets/gallery/fket/electricity_magnetism/electricity_magnetism6.jpg'),
                asset('assets/gallery/fket/electricity_magnetism/electricity_magnetism7.jpg'),
            ],
            28 => [
                asset('assets/gallery/fket/plts/plts.jpg'),
                asset('assets/gallery/fket/plts/plts1.jpg'),
                asset('assets/gallery/fket/plts/plts2.jpg'),
                asset('assets/gallery/fket/plts/plts3.jpg'),
                asset('assets/gallery/fket/plts/plts4.jpg'),
                asset('assets/gallery/fket/plts/plts5.jpg'),
                asset('assets/gallery/fket/plts/plts6.jpg'),
                asset('assets/gallery/fket/plts/plts7.jpg'),
                asset('assets/gallery/fket/plts/plts8.jpg'),
                asset('assets/gallery/fket/plts/plts9.jpg'),
                asset('assets/gallery/fket/plts/plts10.jpg'),
                asset('assets/gallery/fket/plts/plts11.jpg'),
                asset('assets/gallery/fket/plts/plts12.jpg'),
                asset('assets/gallery/fket/plts/plts13.jpg'),
                asset('assets/gallery/fket/plts/plts14.jpg'),
                asset('assets/gallery/fket/plts/plts15.jpg'),
                asset('assets/gallery/fket/plts/plts16.jpg'),
                asset('assets/gallery/fket/plts/plts17.jpg'),
                asset('assets/gallery/fket/plts/plts18.jpg'),
                asset('assets/gallery/fket/plts/plts19.jpg'),
                asset('assets/gallery/fket/plts/plts20.jpg'),
                asset('assets/gallery/fket/plts/plts21.jpg'),
                asset('assets/gallery/fket/plts/plts23.jpg'),
                asset('assets/gallery/fket/plts/plts24.jpg'),
                asset('assets/gallery/fket/plts/plts25.jpg'),
            ],
            29 => [
                asset('assets/gallery/fket/high_voltage/high_voltage.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage1.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage2.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage3.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage4.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage5.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage6.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage7.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage8.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage9.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage10.jpg'),
                asset('assets/gallery/fket/high_voltage/high_voltage11.jpg'),
            ],
            30 => [
                asset('assets/gallery/fket/smart/smart.jpg'),
                asset('assets/gallery/fket/smart/smart1.jpg'),
                asset('assets/gallery/fket/smart/smart2.jpg'),
                asset('assets/gallery/fket/smart/smart3.jpg'),
                asset('assets/gallery/fket/smart/smart4.jpg'),
                asset('assets/gallery/fket/smart/smart5.jpg'),
                asset('assets/gallery/fket/smart/smart6.jpg'),
                asset('assets/gallery/fket/smart/smart7.jpg'),
                asset('assets/gallery/fket/smart/smart8.jpg'),
                asset('assets/gallery/fket/smart/smart9.jpg'),
                asset('assets/gallery/fket/smart/smart10.jpg'),
                asset('assets/gallery/fket/smart/smart11.jpg'),
            ],

            //FTIK
            31 => [
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah1.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah2.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah3.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah4.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah5.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah6.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah7.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah8.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah9.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah10.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah11.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah12.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah13.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah14.jpg'),
                asset('assets/gallery/ftik/mekanika_tanah/mekanika_tanah15.jpg'),
            ],
            32 => [
                asset('assets/gallery/ftik/hidrolika/hidrolika.jpg'),
                asset('assets/gallery/ftik/hidrolika/hidrolika1.jpg'),
                asset('assets/gallery/ftik/hidrolika/hidrolika2.jpg'),
                asset('assets/gallery/ftik/hidrolika/hidrolika3.jpg'),
                asset('assets/gallery/ftik/hidrolika/hidrolika4.jpg'),
                asset('assets/gallery/ftik/hidrolika/hidrolika5.jpg'),
                asset('assets/gallery/ftik/hidrolika/hidrolika6.jpg'),
                asset('assets/gallery/ftik/hidrolika/hidrolika7.jpg'),
                asset('assets/gallery/ftik/hidrolika/hidrolika8.jpg'),
                asset('assets/gallery/ftik/hidrolika/hidrolika9.jpg'),
                asset('assets/gallery/ftik/hidrolika/hidrolika10.jpg'),
            ],
            33 => [
                asset('assets/gallery/ftik/beton/beton.jpg'),
                asset('assets/gallery/ftik/beton/beton1.jpg'),
                asset('assets/gallery/ftik/beton/beton2.jpg'),
                asset('assets/gallery/ftik/beton/beton3.jpg'),
                asset('assets/gallery/ftik/beton/beton4.jpg'),
                asset('assets/gallery/ftik/beton/beton5.jpg'),
                asset('assets/gallery/ftik/beton/beton6.jpg'),
                asset('assets/gallery/ftik/beton/beton7.jpg'),
                asset('assets/gallery/ftik/beton/beton8.jpg'),
                asset('assets/gallery/ftik/beton/beton9.jpg'),
                asset('assets/gallery/ftik/beton/beton10.jpg'),
                asset('assets/gallery/ftik/beton/beton11.jpg'),
                asset('assets/gallery/ftik/beton/beton12.jpg'),
                asset('assets/gallery/ftik/beton/beton13.jpg'),
                asset('assets/gallery/ftik/beton/beton14.jpg'),
            ],
            34 => [
                asset('assets/gallery/ftik/iut/iut.jpg'),
                asset('assets/gallery/ftik/iut/iut1.jpg'),
                asset('assets/gallery/ftik/iut/iut2.jpg'),
                asset('assets/gallery/ftik/iut/iut3.jpg'),
                asset('assets/gallery/ftik/iut/iut4.jpg'),
                asset('assets/gallery/ftik/iut/iut5.jpg'),
                asset('assets/gallery/ftik/iut/iut6.jpg'),
                asset('assets/gallery/ftik/iut/iut7.jpg'),
                asset('assets/gallery/ftik/iut/iut8.jpg'),
            ],
            35 => [
                asset('assets/gallery/ftik/komputasi/komputasi.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi1.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi2.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi3.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi4.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi5.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi6.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi7.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi8.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi9.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi10.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi11.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi12.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi13.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi14.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi15.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi16.jpg'),
                asset('assets/gallery/ftik/komputasi/komputasi17.jpg'),
            ],
            36 => [
                asset('assets/gallery/ftik/chemical/chemical.jpg'),
                asset('assets/gallery/ftik/chemical/chemical1.jpg'),
                asset('assets/gallery/ftik/chemical/chemical2.jpg'),
                asset('assets/gallery/ftik/chemical/chemical3.jpg'),
                asset('assets/gallery/ftik/chemical/chemical4.jpg'),
                asset('assets/gallery/ftik/chemical/chemical5.jpg'),
                asset('assets/gallery/ftik/chemical/chemical6.jpg'),
                asset('assets/gallery/ftik/chemical/chemical7.jpg'),
                asset('assets/gallery/ftik/chemical/chemical8.jpg'),
                asset('assets/gallery/ftik/chemical/chemical9.jpg'),
                asset('assets/gallery/ftik/chemical/chemical10.jpg'),
                asset('assets/gallery/ftik/chemical/chemical11.jpg'),
                asset('assets/gallery/ftik/chemical/chemical12.jpg'),
                asset('assets/gallery/ftik/chemical/chemical13.jpg'),
                asset('assets/gallery/ftik/chemical/chemical14.jpg'),
                asset('assets/gallery/ftik/chemical/chemical15.jpg'),
            ],
            37 => [
                asset('assets/gallery/ftik/wtec/wtec.jpg'),
                asset('assets/gallery/ftik/wtec/wtec1.jpg'),
                asset('assets/gallery/ftik/wtec/wtec2.jpg'),
                asset('assets/gallery/ftik/wtec/wtec3.jpg'),
                asset('assets/gallery/ftik/wtec/wtec4.jpg'),
                asset('assets/gallery/ftik/wtec/wtec5.jpg'),
                asset('assets/gallery/ftik/wtec/wtec7.jpg'),
                asset('assets/gallery/ftik/wtec/wtec8.jpg'),
                asset('assets/gallery/ftik/wtec/wtec9.jpg'),
                asset('assets/gallery/ftik/wtec/wtec10.jpg'),
                asset('assets/gallery/ftik/wtec/wtec11.jpg'),
                asset('assets/gallery/ftik/wtec/wtec12.jpg'),
                asset('assets/gallery/ftik/wtec/wtec13.jpg'),
                asset('assets/gallery/ftik/wtec/wtec14.jpg'),
                asset('assets/gallery/ftik/wtec/wtec15.jpg'),
                asset('assets/gallery/ftik/wtec/wtec16.jpg'),
                asset('assets/gallery/ftik/wtec/wtec17.jpg'),
            ],
        ];

        return view('laboratorium', compact('galleries2'));
    }

    public function forgot_password()
    {
        return view('forgot.password');
    }

}
